version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tsf-app:latest          # tag your built image
    container_name: tsf-app-prod
    ports:
      - "80:80"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: tsf-db-prod
    environment:
      POSTGRES_DB: tsf_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tsf_management"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata_prod:
