services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsf-app-dev
    ports:
      - "80:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./:/var/www/html           # bind mount for instant code changes
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: tsf-db-dev
    environment:
      POSTGRES_DB: tsf_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tsf_management"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata_dev:
